# Week 08: Local/Global Variables

## 0. Import Libraries 

In [7]:
# the "pandas" library is for manipualting datasets
import pandas as pd
import numpy as np
np.random.seed(100)

## 1. Array Continued (Stacking)

<font size='4'>

In [8]:
# 9.1.
x = np.ones((4,))
print(x)
print()
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Concatentate `my_array` and `x`
print(np.concatenate([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=0))
print()
print(np.stack([my_array, x], axis=1))

[1. 1. 1. 1.]

[1. 2. 3. 4. 1. 1. 1. 1.]

[[1. 2. 3. 4.]
 [1. 1. 1. 1.]]

[[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]]


In [12]:
# 9.2. Stack arrays row-wise (by Python's default)
print(np.vstack((my_array, my_2d_array)))

print(np.hstack((my_resized_array, my_2d_array)))

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]


In [19]:
# 9.3.
my_array = np.array([1,2,3,4])
my_resized_array=np.resize(my_array,(2,4))
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

my_stacked_array = np.hstack((my_resized_array, my_2d_array))
print(my_stacked_array)

# if the second argument is an integer, it will split the array into an N equal sub-arrays
# Split `my_stacked_array` horizontally into two equal sub-arrays
print(np.split(my_stacked_array, 2, axis=1))
print("Or")
print(np.hsplit(my_stacked_array, 2))

# Split `my_stacked_array` vertically into two equal sub-arrays
print(np.split(my_stacked_array, 2, axis=0))
print("Or")
print(np.vsplit(my_stacked_array, 2))

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 5 6 7 8]]
[array([[1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]
Or
[array([[1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]
[array([[1, 2, 3, 4, 1, 2, 3, 4]]), array([[1, 2, 3, 4, 5, 6, 7, 8]])]
Or
[array([[1, 2, 3, 4, 1, 2, 3, 4]]), array([[1, 2, 3, 4, 5, 6, 7, 8]])]


In [23]:
# 9.4. Use indices in the form of a numpy array
print(np.split(my_stacked_array, np.array([2,5]), axis=1))
print("Or")
print(np.hsplit(my)stacked_array, np.array([2,5]))

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2863180331.py, line 4)

In [25]:
# 9.5. Let's create a practical example and call back from the blood pressue problem.
# (2, 10, 5) refers to two sites, 10 patients each site, and 5 time points per patient.
BP_3d_arr = np.random.uniform(low=70, high=100, size=(2, 10, 5))
print(BP_3d_arr)
print(BP_3d_arr.shape)

[[[93.34867646 93.38795196 88.3098446  79.27001046 90.93204723]
  [95.78854887 88.75971273 99.47223489 99.29500381 75.00082394]
  [70.69534409 74.82233646 97.70490476 98.6064955  76.32935256]
  [80.81575752 86.48125785 78.15492548 83.81804863 90.88484694]
  [85.0106769  91.48212972 85.77867809 70.04197069 81.8410086 ]
  [84.7650091  82.08640994 80.628949   85.01842958 83.35529886]
  [72.71298365 78.2068876  98.30431293 70.79633924 71.19996069]
  [78.49421079 87.47032511 99.72678409 99.77926712 99.79352117]
  [73.30144993 89.93444338 85.71960503 75.19449729 98.28880735]
  [77.25580258 99.96796807 87.48081445 75.49837002 81.60536266]]

 [[75.69020587 82.32312019 87.84040207 91.49758279 84.60674447]
  [79.28769453 87.32324118 83.25123459 80.79034308 79.63995796]
  [76.24621721 83.53775872 84.75528731 96.97228944 91.88081383]
  [93.10269319 81.26317743 80.31218606 89.65105618 91.3311398 ]
  [73.40612726 73.99086068 83.68117173 74.7920869  98.84925711]
  [95.12847235 85.60482061 76.54816773

In [27]:
# 9.5.1 axis takes one number

BP_3d_arr_mean_1 = np.mean(BP_3d_arr, axis=0)
print(BP_3d_arr_mean_1)
print(BP_3d_arr_mean_1.shape)


[[84.51944117 87.85553607 88.07512333 85.38379662 87.76939585]
 [87.5381217  88.04147696 91.36173474 90.04267344 77.32039095]
 [73.47078065 79.18004759 91.23009603 97.78939247 84.1050832 ]
 [86.95922536 83.87221764 79.23355577 86.73455241 91.10799337]
 [79.20840208 82.7364952  84.72992491 72.4170288  90.34513286]
 [89.94674072 83.84561528 78.58855837 79.53299563 91.36370461]
 [81.96214426 87.00307715 89.95974588 74.16067992 75.09155063]
 [87.10053832 85.82992241 94.81254775 96.97556267 88.69146816]
 [72.84432655 90.95863076 92.28076468 86.90431966 91.50188945]
 [83.11078226 95.97890933 92.27654978 75.18288879 81.89090116]]
(10, 5)


In [30]:
# 9.5.2 axis takes two numbers
#calculates mean of site 1 and 2 at all times points
BP_3d_arr_mean_4 = np.mean(BP_3d_arr, axis=(1,2))
print(BP_3d_arr_mean_4)
print(BP_3d_arr_mean_4.shape)

BP_3d_arr_mean_4 = np.mean(BP_3d_arr, axis=(-2,-1))
print(BP_3d_arr_mean_4)
print(BP_3d_arr_mean_4.shape)

[85.45236797 85.70052937]
(2,)
[85.45236797 85.70052937]
(2,)


In [33]:
# 9.5.3. axis takes three numbers or None
BP_3d_arr_mean_7 = np.mean(BP_3d_arr, axis=(0,1,2))
print(BP_3d_arr_mean_7)

print("OR")
BP_3d_arr_mean_8 = np.mean(BP_3d_arr, axis=(None))
print(BP_3d_arr_mean_8)

85.57644866677343
OR
85.57644866677343


## 2. Local and Global Variables

<font size="4"> 

Most of the variables we've defined so far are "global"

- Stored in working environment
- Can be referenced in other parts of the notebook



<font size = "5">
Example:

In [34]:
message_hello = "hello"
number3       = 3

In [35]:
print(message_hello + " world")
print(number3 * 2)

hello world
6


<font size = "4">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "4">

$f(x,y,z) = x + y + z$

In [38]:
# 2.1. Correct Example:
def fn_add_recommended (x,y,z):
    return x+y+z

print(fn_add_recommended(1,2,5))
print(fn_add_recommended(1,2,10))
    

8
13


In [40]:
# 2.2. Example that runs (but not recommended)
# Python will try to fill in any missing inputs
# with variables in the working environment

def fn_add_notrecommended(x,y):
    return x+y+z
z = 5
print(fn_add_notrecommended(1,2))

z = 10
print(fn_add_notrecommended(1,2))

8
13


In [43]:
# 2.2.1.
#del z # remove variables from a global scope
def print_j():
    j=20
    print(j)

print_j()
print(j)
    

20


NameError: name 'j' is not defined

<font size ="4">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables


### Local variables supercede global variables

In [ ]:
# 2.3.


In [48]:
# 2.4. An exception

depart_ls = ["bios", "edpi", "hshes"]
for id_iter, depart_iter in enumerate(depart_ls):
    print(id_iter, depart_iter)

print("[]")
print(id_iter, depart_iter)

0 bios
1 edpi
2 hshes
[]
2 hshes


In [51]:
# 2.5. This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function are "invisible"
# or "inaccessible" when exiting the function.

def fn_square(x):
    y = x**2
    return y

x = 5 
y = -5
print(fn_square(x =1.2))
print("[]")
print(x, y)

1.44
[]
5 -5


### Local variables are **not** stored in the working environment

In [52]:
# 2.6. The following code assigns a global variable x
x =5
y = 4

print(fn_square(10))

print(x, y)

print(fn_square(20))
print(x, y)

100
5 4
400
5 4


### To permanently modify a variable, use the "global" command

In [ ]:
# 2.7.


### Try it yourself:

<font size = "4">
    
- What happens if we run `modify_x` twice?
- What happens if we add `global y` inside `fn_square`?

In [55]:
# 2.8. Write your own code here
def modify_x():
    global x
    x = x+5

x = 1
print("x={} before modification".format(x))
modify_x()
print("x={} after modification".format(x))

modify_x()
print("x={} after modification again".format(x))

x=1 before modification
x=6 after modification
x=6 after modification again


In [63]:
# 2.9.
def fn_square2(x):
    global y
    y = x**2
    return y

x = 5
y = -5


print (x, y)
z1= fn_square2(1.2)
print(z1)
print(x,y)


5 -5
1.44
5 1.44


### Built-in scope (Variables defined in Python)

<font size='4'>

- Functions such as `print()`, `len()`, `sum()`, `isinstance()` are all built-in functions in Python.
- They are available in any part of your code, so no need to define them.
- Python has a list of variables that are always available to prevent you from using the same names.
- Most of them are error names.

In [66]:
# 2.10
def outer():
    x = "outer->x"

    def inner():
        x = "inner->x"
        print(x)

    inner()
    print(x)

outer()

inner->x
outer->x


### Enclosing scope (Variables defined in enclosing functions)

<font size='4'>
    
- They refer to variables defined in enclosing functions
- Enclosing functions are functions that contain other functions (nested or hierarachical functions)
- Enclosing scope is between local and global scopes in the LEGB rule

In [ ]:
# 2.11
# Define a function that contains another function


## 3. Work with Python scripts

<font size='4'>

Please open `week_08_main_1.py` and `week_08_main_2.py`.